apiVersion: v1
kind: Service
metadata:
  name: banking-devsecops-api
  namespace: banking-devsecops
spec:
  type: ClusterIP
  selector:
    app: banking-devsecops-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
